repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: check-yaml
          - id: trailing-whitespace
          - id: check-added-large-files
            args:
                - --maxkb=1000
          - id: check-vcs-permalinks
          - id: check-merge-conflict
          - id: mixed-line-ending
            args:
                - --fix=lf
    - repo: https://github.com/abravalheri/validate-pyproject
      rev: v0.16
      hooks:
          - id: validate-pyproject
    - repo: https://github.com/pycqa/isort
      rev: 5.13.2
      hooks:
          - id: isort
            name: isort (python)
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: "v1.9.0"
      hooks:
          - id: mypy
            exclude: "^py/torch_tensorrt/fx|^examples|^tests|^py/torch_tensorrt/dynamo/_experimental|^tools|^docs|noxfile.py|setup.py|versions.py"
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.3.3
      hooks:
          - id: ruff
    - repo: https://github.com/psf/black
      rev: 24.3.0
      hooks:
          - id: black
    - repo: https://github.com/crate-ci/typos
      rev: v1.22.9
      hooks:
          - id: typos
    - repo: https://github.com/astral-sh/uv-pre-commit
      # uv version.
      rev: 0.4.10
      hooks:
          # Update the uv lockfile
          - id: uv-lock
